### ISSUE TITLE
Paloalto 10.2.5 licensed eval does not load re EVE-NG

### ISSUE THREAD

**Issue by dean-itsatestdotnetwork** [hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG#17]
I am using

As soon as I log in I get:
the system is going down for system halt NOW 

I am using QEMU 2.12.0 and have also tried tpl(2.12.0)

A few days ago I tried all QEMU versions. Same result

**Comment by dean-itsatestdotnetwork** [comment]
10.0.4-eval also fails. I have managed to start 10.1.0

**Comment by hegdepavankumar** [comment]
> 10.0.4-eval also fails. I have managed to start 10.1.0

I will update you soon!! please try with any other version available...

**Comment by amzad00007** [comment]
its loaded but its showing wrong or incorrect password
and after some time 
Paloalto 10.2.5 licensed eval is turned off auto matically
