### ISSUE TITLE
Help in IDS image files

### ISSUE THREAD

**Issue by vinayk028** [hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG#2]
helo brother , 
Can u send me the IDS Disk image file in case u have ? its very needed for me  now ...

**Comment by vinayk028** [comment]
we need DISK image file to add that IDS file in GNS3

We are doing  a project in IDS using GNS3 .. for that we need files

**Comment by vinayk028** [comment]
> > helo brother , Can u send me the IDS Disk image file in case u have ? its very needed for me now ...
> 
> can you please describe which vendor ? version ? something...
we need DISK image file to add that IDS file in GNS3

We are doing  a project in IDS using GNS3 .. for that we need files

**Comment by vinayk028** [comment]
we need DISK image file to add that IDS file in GNS3

We are doing  a project in IDS using GNS3 .. for that we need files

**Comment by hegdepavankumar** [comment]
> we need DISK image file to add that IDS file in GNS3
> 
> We are doing a project in IDS using GNS3 .. for that we need files

Sorry Brother I don't have both IPS and IDS disk files; my Cisco Premium account also expired.
