### ISSUE TITLE
win10 

### ISSUE THREAD

**Issue by njeck** [hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG#4]
please what  is the login for your win-10-x64-20H2v2
![Screenshot 2023-12-15 092204](https://github.com/hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG/assets/84487248/5f39b4a6-5e7e-4ee0-b047-5929f3c88dc4)

**Comment by hegdepavankumar** [comment]
> please what is the login for your win-10-x64-20H2v2 ![Screenshot 2023-12-15 092204](https://private-user-images.githubusercontent.com/84487248/290766714-5f39b4a6-5e7e-4ee0-b047-5929f3c88dc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTE4ODksIm5iZiI6MTcwMjY1MTU4OSwicGF0aCI6Ii84NDQ4NzI0OC8yOTA3NjY3MTQtNWYzOWI0YTYtNWU3ZS00ZWUwLWIwNDctNTkyOWYzYzg4ZGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE0NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjRkNWFkMGU2NTk0ZDU3YTAyOTU2YzkyY2E1OTNkNjY2MWRhOGIwYjNlNDgyNjQxYTgxZmZmZGY0OGYwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.68rn5ex-VXb75mgDt4VJD4SBIF8AysYh7o3fZJVLlyg)

Hi, thanks for visiting!! 
The default password is : Test123

**Comment by hegdepavankumar** [comment]
> > please what is the login for your win-10-x64-20H2v2 ![Screenshot 2023-12-15 092204](https://private-user-images.githubusercontent.com/84487248/290766714-5f39b4a6-5e7e-4ee0-b047-5929f3c88dc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTE4ODksIm5iZiI6MTcwMjY1MTU4OSwicGF0aCI6Ii84NDQ4NzI0OC8yOTA3NjY3MTQtNWYzOWI0YTYtNWU3ZS00ZWUwLWIwNDctNTkyOWYzYzg4ZGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE0NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjRkNWFkMGU2NTk0ZDU3YTAyOTU2YzkyY2E1OTNkNjY2MWRhOGIwYjNlNDgyNjQxYTgxZmZmZGY0OGYwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.68rn5ex-VXb75mgDt4VJD4SBIF8AysYh7o3fZJVLlyg)
> 
> Hi, thanks for visiting!! The default password is : Test123

If it is not working also try with - Test@123
Thank you!!
