### ISSUE TITLE
VirtualBox Image is flawed

### ISSUE THREAD

**Issue by Chippel** [hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG#6]
The VM does not give me an IP address and the field is blank. It looks like this:
"https://:8000/upload"

I'm already using a host only adapted. But even with a Nat Adapter in VirtualBox I can't access the url.

**Comment by hegdepavankumar** [comment]
I didn't get your query,? Which image you are trying to install? windows PC, Server, .....

**Comment by Chippel** [comment]
You quoted in your install instructions that a user have to install the GNS3.ova

I downloaded it and I imported it in VB. When clicking on start I receive a notification that I also have to enable Nat. So I went in the settings of the VM and enabled Nat. After that I was able to boot the machine. 

When the machine successfully started I won't get an IP address wether I go with Nat, no NAT etc. I can't change the ip address of the machine or modify it because I do not have credentials and you did not mention any on your page. 

So all I can see after booting up the machine is an empty IP address with port 8000.

**Comment by hegdepavankumar** [comment]
> You quoted in your install instructions that a user have to install the GNS3.ova
> 
> I downloaded it and I imported it in VB. When clicking on start I receive a notification that I also have to enable Nat. So I went in the settings of the VM and enabled Nat. After that I was able to boot the machine.
> 
> When the machine successfully started I won't get an IP address wether I go with Nat, no NAT etc. I can't change the ip address of the machine or modify it because I do not have credentials and you did not mention any on your page.
> 
> So all I can see after booting up the machine is an empty IP address with port 8000.

Try this link ..this is the official website for GNS3 VM for all virtualization platforms..!  
link: [https://gns3.com/software/download-vm](https://gns3.com/software/download-vm)

**Comment by Chippel** [comment]
Thanks. I thought I have to use your VB image. So I assume I could also use the VMware image?

I set it up with the VMware Image but I always receive the message that the licences is invalid. Do you have a tutorial about how to fix this?

**Comment by hegdepavankumar** [comment]
> Thanks. I thought I have to use your VB image. So I assume I could also use the VMware image?
> 
> I set it up with the VMware Image but I always receive the message that the licences is invalid. Do you have a tutorial about how to fix this?

 Your Welcome ......Try to find out how to add the license key ..on YouTube! so many videos are available. License keys are available in my Github repo kindly checkout.    Thank you!!

**Comment by Chippel** [comment]
Tried a bit and I have to tell that the licence key does not seem to work with VmwareVM cuz it's invalid. I found several videos on the internet but they suggest using a python3 script to create a licence. Do you have it uploaded here and I'm just blind?
