### ISSUE TITLE
Palo Alto Eval Version Reboots

### ISSUE THREAD

**Issue by Chippel** [hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG#7]
Not sure if it's right here but it seems like the PA eval image is not working probably. The VM restarts after like 5 minutes and I'm not able to do anything. Seems like this error only occurs when using the eval VM.

**Comment by hegdepavankumar** [comment]
> Not sure if it's right here but it seems like the PA eval image is not working probably. The VM restarts after like 5 minutes and I'm not able to do anything. Seems like this error only occurs when using the eval VM.

Hi [Chippel](https://github.com/Chippel), Thanks for informing I'll check and let you know...make sure you are following all the file formats of eve-ng like folder name and qemu name......anyway I'll check Okay.!!

**Comment by hegdepavankumar** [comment]
Try to be part of our community, Resource Hub Telegram Group, there you'll get instant support from other community people. Link: [Resource Hub](https://t.me/resourcehub1). Also, I'll update and upload the images in that group.

**Comment by hegdepavankumar** [comment]
Hi Hi [Chippel](https://github.com/Chippel),


👉👉🔴Attention🔴👈👈

EVE-NG(All vendor Images like Cisco, Palo Alto, and Fortigate Available!!!)
----------------
(Encrypted)
Folder Link: [Click Here](https://mega.nz/folder/E1xCXCzQ)   

(Decrypt Key)
Key: 3djrXU8rQzprcDAAlPw7ew


Join Our Community Group: [Join Now](https://t.me/resourcehub1)

**Comment by dean-itsatestdotnetwork** [comment]
What was the fix here? The issue was simply closed. I have a simialr issue and another post describing this

**Comment by 0xfka** [comment]
> What was the fix here? The issue was simply closed. I have a simialr issue and another post describing this

I fixed it by adding -cpu host parameter in gns3 and giving more resurces to vm on PA-VM-KVM-8.1.0.qcow2.
