### ISSUE TITLE
credentials to the images

### ISSUE THREAD

**Issue by blahblah2206** [hegdepavankumar/Cisco-Images-for-GNS3-and-EVE-NG#9]
hi, really appreciate these images, though I didn't find logon credentials to these images, specifically for the Palo Alto paranoma image. Tried the default admin/admin but didn't work.

**Comment by blahblah2206** [comment]
never mind. I got it.

**Comment by blahblah2206** [comment]
resolved.

**Comment by esdotzed** [comment]
@blahblah2206 so what is the pw??

**Comment by blahblah2206** [comment]
admin/Admin123
